name: app_template_flavor_flutter
description: "App template with flafor resource configured and using 3.24.2 flutter version via fvm"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_flavor: ^3.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
